language: python
python:
  - "3.10"
  - "3.11"
env:
  - DJANGO=4.2.4

install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - sudo mkdir /var/log/www-data
  - sudo chown travis:travis /var/log/www-data

script:
  - python manage.py test
