language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=2.0.1
  - DJANGO=2.0.2
  - DJANGO=2.0.8
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations
  - python manage.py migrate
# command to run tests
script:
  - python manage.py test
