# Generated by Django 2.0.1 on 2018-05-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('accesstype', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camelot.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('dname', models.CharField(default='', max_length=100)),
                ('profile_pic', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='camelot.Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='requestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='members',
            field=models.ManyToManyField(related_name='groupmembers', to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupowner', to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='contributors',
            field=models.ManyToManyField(related_name='albumcontributors', to='camelot.Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='groups',
            field=models.ManyToManyField(related_name='albumgroup', to='camelot.FriendGroup'),
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camelot.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('requester', 'requestee')},
        ),
    ]
