# Generated by Django 2.0.1 on 2018-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
