# Generated by Django 2.0.1 on 2018-05-18 09:33

from django.db import migrations
from ..controllers.albumcontroller import ThumbFromBuffer
from ..constants import PREFIX
from os import makedirs

def create_thumbs(apps, schema_editor):
    '''
    We can't import the model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    photos = apps.get_model('camelot', 'Photo')
    for photo in photos.objects.all():
        thumbname = PREFIX + 'thumbs/{}/{}/{}.png'.format(photo.uploader.user.id, photo.album.id, photo.id)
        makedirs("/".join(thumbname.split("/")[:-1]), exist_ok=True)
        with open(photo.filename, 'rb') as rawpic:
            rawpic.seek(0)
            ThumbFromBuffer(rawpic).save(thumbname)
        photo.thumb = thumbname
        photo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0002_photo_thumb'),
    ]

    operations = [
        migrations.RunPython(create_thumbs),
    ]
