# Generated by Django 2.0.1 on 2018-05-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0003_auto_20180518_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.CharField(max_length=200),
        ),
    ]
