# Generated by Django 2.0.1 on 2018-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0005_photo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='midsize',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
