# Generated by Django 2.0.1 on 2018-06-11 04:55

from django.db import migrations
from ..controllers.albumcontroller import ThumbFromBuffer
from ..constants import PREFIX, MIDHEIGHT
from os import makedirs

def create_mids(apps, schema_editor):
    '''
    We can't import the model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    photos = apps.get_model('camelot', 'Photo')
    for photo in photos.objects.all():
        midname = PREFIX + 'mid/{}/{}/{}.png'.format(photo.uploader.user.id, photo.album.id, photo.id)
        makedirs("/".join(midname.split("/")[:-1]), exist_ok=True)
        with open(photo.filename, 'rb') as rawpic:
            rawpic.seek(0)
            ThumbFromBuffer(rawpic, MIDHEIGHT).save(midname)
        photo.midsize = midname
        photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0006_photo_midsize'),
    ]

    operations = [
        migrations.RunPython(create_mids),
    ]

