# Generated by Django 2.0.1 on 2018-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0007_auto_20180611_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='midsize',
            field=models.CharField(max_length=200),
        ),
    ]
