# Generated by Django 2.0.1 on 2018-06-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0008_auto_20180611_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='imgtype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
