# Generated by Django 2.0.1 on 2018-06-17 03:16

from django.db import migrations
from io import BytesIO
from PIL import Image

def create_mime(apps, schema_editor):
    photos = apps.get_model('camelot', 'Photo')
    for photo in photos.objects.all():
        with open(photo.filename, 'rb') as rawpic:
            rawpic.seek(0)
            with Image.open(BytesIO(rawpic.read())) as img:
                photo.imgtype = Image.MIME[img.format]
        photo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0009_photo_imgtype'),
    ]

    operations = [
        migrations.RunPython(create_mime),
    ]
