# Generated by Django 2.0.3 on 2018-07-28 02:50

from django.db import migrations
from os import unlink
from ..controllers.albumcontroller import ThumbFromBuffer
from ..constants import MIDHEIGHT


def to_jpeg(apps, schema_editor):
    photos = apps.get_model('camelot', 'Photo')
    for photo in photos.objects.all():
        oldmid = photo.midsize
        oldthumb = photo.thumb
        photo.midsize = oldmid.replace(".png", ".jpg")
        photo.thumb = oldthumb.replace(".png", ".jpg")

        # create new files
        with open(photo.filename, "rb") as fi:
            fi.seek(0)
            ThumbFromBuffer(fi, photo.thumb)
            fi.seek(0)
            ThumbFromBuffer(fi, photo.midsize, MIDHEIGHT)

        photo.save()

        # delete old thumbs and mids
        if photo.thumb != oldthumb:
            try:
                unlink(oldthumb)
            except Exception as e:
                print("could not unlink {}".format(oldthumb))
                print(e)
        if photo.midsize != oldmid:
            try:
                unlink(oldmid)
            except Exception as e:
                print("could not unlink {}".format(oldmid))
                print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('camelot', '0012_photo_exiforientation'),
    ]

    operations = [
        migrations.RunPython(to_jpeg),
    ]
